### ISSUE TITLE
Update duolibre on PyPI

### ISSUE THREAD

**Issue by vecna13** [evan-goode/duolibre#4]
Thanks for providing this great tool! The current version on PyPI is from 2020 and does not include the recent change to support QR codes. It would be helpful to be able to install duolibre using pip and use it to register from QR code.

**Comment by evan-goode** [comment]
Thanks for noticing that, I may actually just take it off PyPI and change the README to recommend cloning and running it. Or installing via pip by the repository's clone URL. I'd rather not have to remember to release to PyPI, and there's little reason to, since probably nothing depends on this package. This is the kind of thing that users should probably be reading before they run it.

**Comment by evan-goode** [comment]
Closing this, I yanked the only published version from PyPI and updated the README to recommend installing via pip directly from the GitHub URL or running as a Nix flake.
